// Generated by gencpp from file am_planning/PathFromPolygonRequest.msg
// DO NOT EDIT!


#ifndef AM_PLANNING_MESSAGE_PATHFROMPOLYGONREQUEST_H
#define AM_PLANNING_MESSAGE_PATHFROMPOLYGONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace am_planning
{
template <class ContainerAllocator>
struct PathFromPolygonRequest_
{
  typedef PathFromPolygonRequest_<ContainerAllocator> Type;

  PathFromPolygonRequest_()
    : border()
    , start()  {
    }
  PathFromPolygonRequest_(const ContainerAllocator& _alloc)
    : border(_alloc)
    , start(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _border_type;
  _border_type border;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
  _start_type start;




  typedef boost::shared_ptr< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathFromPolygonRequest_

typedef ::am_planning::PathFromPolygonRequest_<std::allocator<void> > PathFromPolygonRequest;

typedef boost::shared_ptr< ::am_planning::PathFromPolygonRequest > PathFromPolygonRequestPtr;
typedef boost::shared_ptr< ::am_planning::PathFromPolygonRequest const> PathFromPolygonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_planning::PathFromPolygonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3e2c61cc3c0e9f725d8957f9316e575";
  }

  static const char* value(const ::am_planning::PathFromPolygonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3e2c61cc3c0e9f7ULL;
  static const uint64_t static_value2 = 0x25d8957f9316e575ULL;
};

template<class ContainerAllocator>
struct DataType< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_planning/PathFromPolygonRequest";
  }

  static const char* value(const ::am_planning::PathFromPolygonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PolygonStamped border\n\
geometry_msgs/PoseStamped start\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PolygonStamped\n\
# This represents a Polygon with reference coordinate frame and timestamp\n\
Header header\n\
Polygon polygon\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::am_planning::PathFromPolygonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.border);
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PathFromPolygonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_planning::PathFromPolygonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_planning::PathFromPolygonRequest_<ContainerAllocator>& v)
  {
    s << indent << "border: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.border);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_PLANNING_MESSAGE_PATHFROMPOLYGONREQUEST_H
