// Generated by gencpp from file am_planning/PolygonsFromPolygonResponse.msg
// DO NOT EDIT!


#ifndef AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGONRESPONSE_H
#define AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>

namespace am_planning
{
template <class ContainerAllocator>
struct PolygonsFromPolygonResponse_
{
  typedef PolygonsFromPolygonResponse_<ContainerAllocator> Type;

  PolygonsFromPolygonResponse_()
    : outputPolygons()  {
    }
  PolygonsFromPolygonResponse_(const ContainerAllocator& _alloc)
    : outputPolygons(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PolygonStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::other >  _outputPolygons_type;
  _outputPolygons_type outputPolygons;




  typedef boost::shared_ptr< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PolygonsFromPolygonResponse_

typedef ::am_planning::PolygonsFromPolygonResponse_<std::allocator<void> > PolygonsFromPolygonResponse;

typedef boost::shared_ptr< ::am_planning::PolygonsFromPolygonResponse > PolygonsFromPolygonResponsePtr;
typedef boost::shared_ptr< ::am_planning::PolygonsFromPolygonResponse const> PolygonsFromPolygonResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "414d7f5ada26496d7bcc09d90c03607c";
  }

  static const char* value(const ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x414d7f5ada26496dULL;
  static const uint64_t static_value2 = 0x7bcc09d90c03607cULL;
};

template<class ContainerAllocator>
struct DataType< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_planning/PolygonsFromPolygonResponse";
  }

  static const char* value(const ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PolygonStamped[] outputPolygons\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PolygonStamped\n\
# This represents a Polygon with reference coordinate frame and timestamp\n\
Header header\n\
Polygon polygon\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outputPolygons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PolygonsFromPolygonResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_planning::PolygonsFromPolygonResponse_<ContainerAllocator>& v)
  {
    s << indent << "outputPolygons[]" << std::endl;
    for (size_t i = 0; i < v.outputPolygons.size(); ++i)
    {
      s << indent << "  outputPolygons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.outputPolygons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGONRESPONSE_H
