// Generated by gencpp from file am_planning/PolygonsFromPolygon.msg
// DO NOT EDIT!


#ifndef AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGON_H
#define AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGON_H

#include <ros/service_traits.h>


#include <am_planning/PolygonsFromPolygonRequest.h>
#include <am_planning/PolygonsFromPolygonResponse.h>


namespace am_planning
{

struct PolygonsFromPolygon
{

typedef PolygonsFromPolygonRequest Request;
typedef PolygonsFromPolygonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PolygonsFromPolygon
} // namespace am_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::am_planning::PolygonsFromPolygon > {
  static const char* value()
  {
    return "38f673104d6845a725025970096b7577";
  }

  static const char* value(const ::am_planning::PolygonsFromPolygon&) { return value(); }
};

template<>
struct DataType< ::am_planning::PolygonsFromPolygon > {
  static const char* value()
  {
    return "am_planning/PolygonsFromPolygon";
  }

  static const char* value(const ::am_planning::PolygonsFromPolygon&) { return value(); }
};


// service_traits::MD5Sum< ::am_planning::PolygonsFromPolygonRequest> should match 
// service_traits::MD5Sum< ::am_planning::PolygonsFromPolygon > 
template<>
struct MD5Sum< ::am_planning::PolygonsFromPolygonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::am_planning::PolygonsFromPolygon >::value();
  }
  static const char* value(const ::am_planning::PolygonsFromPolygonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::am_planning::PolygonsFromPolygonRequest> should match 
// service_traits::DataType< ::am_planning::PolygonsFromPolygon > 
template<>
struct DataType< ::am_planning::PolygonsFromPolygonRequest>
{
  static const char* value()
  {
    return DataType< ::am_planning::PolygonsFromPolygon >::value();
  }
  static const char* value(const ::am_planning::PolygonsFromPolygonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::am_planning::PolygonsFromPolygonResponse> should match 
// service_traits::MD5Sum< ::am_planning::PolygonsFromPolygon > 
template<>
struct MD5Sum< ::am_planning::PolygonsFromPolygonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::am_planning::PolygonsFromPolygon >::value();
  }
  static const char* value(const ::am_planning::PolygonsFromPolygonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::am_planning::PolygonsFromPolygonResponse> should match 
// service_traits::DataType< ::am_planning::PolygonsFromPolygon > 
template<>
struct DataType< ::am_planning::PolygonsFromPolygonResponse>
{
  static const char* value()
  {
    return DataType< ::am_planning::PolygonsFromPolygon >::value();
  }
  static const char* value(const ::am_planning::PolygonsFromPolygonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AM_PLANNING_MESSAGE_POLYGONSFROMPOLYGON_H
