// Generated by gencpp from file am_driver/BeaconPositions.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_MESSAGE_BEACONPOSITIONS_H
#define AM_DRIVER_MESSAGE_BEACONPOSITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace am_driver
{
template <class ContainerAllocator>
struct BeaconPositions_
{
  typedef BeaconPositions_<ContainerAllocator> Type;

  BeaconPositions_()
    : header()
    , numBeacons(0)
    , isLocked(false)
    , beaconId()
    , beaconPosX()
    , beaconPosY()
    , beaconPosZ()  {
    }
  BeaconPositions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , numBeacons(0)
    , isLocked(false)
    , beaconId(_alloc)
    , beaconPosX(_alloc)
    , beaconPosY(_alloc)
    , beaconPosZ(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _numBeacons_type;
  _numBeacons_type numBeacons;

   typedef uint8_t _isLocked_type;
  _isLocked_type isLocked;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _beaconId_type;
  _beaconId_type beaconId;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _beaconPosX_type;
  _beaconPosX_type beaconPosX;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _beaconPosY_type;
  _beaconPosY_type beaconPosY;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _beaconPosZ_type;
  _beaconPosZ_type beaconPosZ;




  typedef boost::shared_ptr< ::am_driver::BeaconPositions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver::BeaconPositions_<ContainerAllocator> const> ConstPtr;

}; // struct BeaconPositions_

typedef ::am_driver::BeaconPositions_<std::allocator<void> > BeaconPositions;

typedef boost::shared_ptr< ::am_driver::BeaconPositions > BeaconPositionsPtr;
typedef boost::shared_ptr< ::am_driver::BeaconPositions const> BeaconPositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver::BeaconPositions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver::BeaconPositions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'am_driver': ['/home/agneev/catkin_ws/src/hrp/am_driver/msg', '/home/agneev/catkin_ws/src/hrp/am_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::BeaconPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::BeaconPositions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::BeaconPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::BeaconPositions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::BeaconPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::BeaconPositions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver::BeaconPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46028d064b93a5222a09c4bb5198c03a";
  }

  static const char* value(const ::am_driver::BeaconPositions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46028d064b93a522ULL;
  static const uint64_t static_value2 = 0x2a09c4bb5198c03aULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver::BeaconPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver/BeaconPositions";
  }

  static const char* value(const ::am_driver::BeaconPositions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver::BeaconPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 numBeacons\n\
bool isLocked\n\
string[] beaconId\n\
float32[] beaconPosX\n\
float32[] beaconPosY\n\
float32[] beaconPosZ\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::am_driver::BeaconPositions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver::BeaconPositions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.numBeacons);
      stream.next(m.isLocked);
      stream.next(m.beaconId);
      stream.next(m.beaconPosX);
      stream.next(m.beaconPosY);
      stream.next(m.beaconPosZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BeaconPositions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver::BeaconPositions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver::BeaconPositions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "numBeacons: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numBeacons);
    s << indent << "isLocked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isLocked);
    s << indent << "beaconId[]" << std::endl;
    for (size_t i = 0; i < v.beaconId.size(); ++i)
    {
      s << indent << "  beaconId[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.beaconId[i]);
    }
    s << indent << "beaconPosX[]" << std::endl;
    for (size_t i = 0; i < v.beaconPosX.size(); ++i)
    {
      s << indent << "  beaconPosX[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beaconPosX[i]);
    }
    s << indent << "beaconPosY[]" << std::endl;
    for (size_t i = 0; i < v.beaconPosY.size(); ++i)
    {
      s << indent << "  beaconPosY[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beaconPosY[i]);
    }
    s << indent << "beaconPosZ[]" << std::endl;
    for (size_t i = 0; i < v.beaconPosZ.size(); ++i)
    {
      s << indent << "  beaconPosZ[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beaconPosZ[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_MESSAGE_BEACONPOSITIONS_H
