// Generated by gencpp from file am_driver/Loop.msg
// DO NOT EDIT!


#ifndef AM_DRIVER_MESSAGE_LOOP_H
#define AM_DRIVER_MESSAGE_LOOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <am_driver/LoopData.h>
#include <am_driver/LoopData.h>
#include <am_driver/LoopData.h>
#include <am_driver/LoopData.h>
#include <am_driver/LoopData.h>
#include <am_driver/LoopData.h>

namespace am_driver
{
template <class ContainerAllocator>
struct Loop_
{
  typedef Loop_<ContainerAllocator> Type;

  Loop_()
    : header()
    , frontCenter(0)
    , frontRight(0)
    , rearLeft(0)
    , rearRight(0)
    , A0()
    , N()
    , F()
    , G1()
    , G2()
    , G3()  {
    }
  Loop_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frontCenter(0)
    , frontRight(0)
    , rearLeft(0)
    , rearRight(0)
    , A0(_alloc)
    , N(_alloc)
    , F(_alloc)
    , G1(_alloc)
    , G2(_alloc)
    , G3(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _frontCenter_type;
  _frontCenter_type frontCenter;

   typedef int32_t _frontRight_type;
  _frontRight_type frontRight;

   typedef int32_t _rearLeft_type;
  _rearLeft_type rearLeft;

   typedef int32_t _rearRight_type;
  _rearRight_type rearRight;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _A0_type;
  _A0_type A0;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _N_type;
  _N_type N;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _F_type;
  _F_type F;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _G1_type;
  _G1_type G1;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _G2_type;
  _G2_type G2;

   typedef  ::am_driver::LoopData_<ContainerAllocator>  _G3_type;
  _G3_type G3;




  typedef boost::shared_ptr< ::am_driver::Loop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_driver::Loop_<ContainerAllocator> const> ConstPtr;

}; // struct Loop_

typedef ::am_driver::Loop_<std::allocator<void> > Loop;

typedef boost::shared_ptr< ::am_driver::Loop > LoopPtr;
typedef boost::shared_ptr< ::am_driver::Loop const> LoopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_driver::Loop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_driver::Loop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'am_driver': ['/home/agneev/catkin_ws/src/hrp/am_driver/msg', '/home/agneev/catkin_ws/src/hrp/am_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::Loop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_driver::Loop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::Loop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_driver::Loop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::Loop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_driver::Loop_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_driver::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82dbea7fa784303d18afb38f52cd0d3a";
  }

  static const char* value(const ::am_driver::Loop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82dbea7fa784303dULL;
  static const uint64_t static_value2 = 0x18afb38f52cd0d3aULL;
};

template<class ContainerAllocator>
struct DataType< ::am_driver::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_driver/Loop";
  }

  static const char* value(const ::am_driver::Loop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_driver::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 frontCenter\n\
int32 frontRight\n\
int32 rearLeft\n\
int32 rearRight\n\
LoopData A0\n\
LoopData N\n\
LoopData F\n\
LoopData G1\n\
LoopData G2\n\
LoopData G3\n\
\n\
 \n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: am_driver/LoopData\n\
int32 frontCenter\n\
int32 frontRight\n\
int32 rearLeft\n\
int32 rearRight\n\
 \n\
";
  }

  static const char* value(const ::am_driver::Loop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_driver::Loop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frontCenter);
      stream.next(m.frontRight);
      stream.next(m.rearLeft);
      stream.next(m.rearRight);
      stream.next(m.A0);
      stream.next(m.N);
      stream.next(m.F);
      stream.next(m.G1);
      stream.next(m.G2);
      stream.next(m.G3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Loop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_driver::Loop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_driver::Loop_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frontCenter: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frontCenter);
    s << indent << "frontRight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frontRight);
    s << indent << "rearLeft: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rearLeft);
    s << indent << "rearRight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rearRight);
    s << indent << "A0: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.A0);
    s << indent << "N: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.N);
    s << indent << "F: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.F);
    s << indent << "G1: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.G1);
    s << indent << "G2: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.G2);
    s << indent << "G3: ";
    s << std::endl;
    Printer< ::am_driver::LoopData_<ContainerAllocator> >::stream(s, indent + "  ", v.G3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_DRIVER_MESSAGE_LOOP_H
